# Generated by Django 4.1.7 on 2023-03-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item/')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ManyToManyField(to='branch.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
