# Generated by Django 4.1.7 on 2023-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
