# Generated by Django 4.1.7 on 2023-03-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_subscription_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_level',
            field=models.IntegerField(default=1),
        ),
    ]
