# Generated by Django 4.1.7 on 2023-03-14 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_branch_is_default'),
        ('subscription', '0003_alter_subscription_subscription_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='company',
        ),
        migrations.AddField(
            model_name='subscription',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
