# Generated by Django 4.1.7 on 2023-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0006_branch_placeholder_item_branch_placeholder_meals'),
        ('item', '0004_alter_item_description_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='group/')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ManyToManyField(to='branch.branch')),
                ('item', models.ManyToManyField(to='item.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
