# Generated by Django 4.1.7 on 2023-03-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='video_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
