# Generated by Django 4.1.7 on 2023-03-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_trade_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
