# Generated by Django 4.1.7 on 2023-03-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_no',
        ),
    ]
