# Generated by Django 4.1.7 on 2023-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_company_address_remove_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
