# Generated by Django 4.1.7 on 2023-03-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type_status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
