# Generated by Django 4.1.7 on 2023-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
