# Generated by Django 4.1.7 on 2023-03-13 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('branch', '0006_branch_placeholder_item_branch_placeholder_meals'),
        ('item', '0004_alter_item_description_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('QR_counter', models.IntegerField(default=0)),
                ('status', models.CharField(default='Available', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('branch', models.ManyToManyField(to='branch.branch')),
                ('group', models.ManyToManyField(to='group.group')),
                ('item', models.ManyToManyField(to='item.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('branch_id', 'company_id', 'date')},
            },
        ),
    ]
