# Generated by Django 4.1.7 on 2023-03-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarymenu',
            name='promo_image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/'),
        ),
        migrations.AddField(
            model_name='primarymenu',
            name='promo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='primarymenu',
            name='promo_vid',
            field=models.URLField(blank=True, null=True),
        ),
    ]
