# Generated by Django 4.1.7 on 2023-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_primarymenu_promo_image_primarymenu_promo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='video_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
