# Generated by Django 4.1.7 on 2023-03-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='QR_counter',
            field=models.IntegerField(default=0),
        ),
    ]
