# Generated by Django 4.1.7 on 2023-03-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_branch_qr_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
