# Generated by Django 4.1.7 on 2023-03-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_branch_placeholder_item_branch_placeholder_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
