# Generated by Django 4.1.7 on 2023-03-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_branch_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
