# Generated by Django 4.1.7 on 2023-03-15 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_alter_branch_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_update', models.BooleanField(default=False)),
                ('change_log', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(default='Bangladesh', max_length=255)),
                ('time_zone', models.CharField(default='Asia/Dhaka', max_length=255)),
                ('currency', models.CharField(default='EN', max_length=255)),
                ('language', models.CharField(default='BDT', max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Date_time_format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_format', models.CharField(default='dd-mm-yyyy', max_length=255)),
                ('currency_precision', models.CharField(default=3, max_length=50)),
                ('time_format', models.CharField(default='hh:mm:ss', max_length=255)),
                ('number_format', models.CharField(default='#,###.##', max_length=255)),
                ('begin_week', models.CharField(default='Sunday', max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
