# Generated by Django 4.1.7 on 2023-03-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_alter_date_time_format_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localization',
            name='currency',
            field=models.CharField(default='BDT', max_length=255),
        ),
        migrations.AlterField(
            model_name='localization',
            name='language',
            field=models.CharField(default='EN', max_length=255),
        ),
        migrations.AlterField(
            model_name='localization',
            name='time_zone',
            field=models.CharField(default='UTC+06:00', max_length=255),
        ),
    ]
